# Generated by Django 5.1.2 on 2024-11-07 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_studentcontactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontactinfo',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.'), django.core.validators.RegexValidator(message='Incorrect email', regex='.+@.+')]),
        ),
        migrations.AlterField(
            model_name='studentcontactinfo',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\d{10}$')]),
        ),
    ]
